### ISSUE TITLE
Error when subscribing to an entity from Orion

### ISSUE THREAD

**Issue by MRROOX** [smartsdk/ngsi-timeseries-api#254]
**ERROR:app:Exception on /v2/notify [POST]**

Hello, the context of the bug is as follows:

- I'm working on an example to get a series of data using Fiware. 

- When I try to subscribe an entity using Orion's APIs (http://localhost:1026/v2/subscriptions/):

 [*] Content-type : application/json

```
 {
  "description": "Suscripción DHT22",
  "subject": {
    "entities": [
      {
        "idPattern": "DHT22.*",
        "type": "DHT22"
      }
    ],
    "condition": {
      "attrs": [
        "temperature",
        "relativeHumidity"
      ]
    }
  },
  "notification": {
    "attrs": [
      "id",
      "temperature",
      "relativeHumidity",
      "dateObserved",
      "location"
    ],
    "http": {
      "url": "http://quantumleap:8668/v2/notify"
    },
      "metadata": ["dateCreated", "dateModified"]
  },
  "throttling": 1
}
```
**The following ERROR occurs in the Quantum Leap Container.**
```
INFO:reporter.reporter:Received payload: [{'id': 'DHT22001', 'type': 'DHT22', 'temperature': {'type': 'Number', 'value': 29, 'metadata': {'dateCreated': {'type': 'DateTime', 'value': '2019-09-25T04:32:34.00Z'}, 'dateModified': {'type': 'DateTime', 'value': '2019-09-25T04:32:41.00Z'}}}, 'relativeHumidity': {'type': 'Number', 'value': '0', 'metadata': {'dateCreated': {'type': 'DateTime', 'value': '2019-09-25T04:32:34.00Z'}, 'dateModified': {'type': 'DateTime', 'value': '2019-09-25T04:32:34.00Z'}}}, 'dateObserved': {'type': 'DateTime', 'value': '2019-09-30T23:00:00.00Z', 'metadata': {'dateCreated': {'type': 'DateTime', 'value': '2019-09-25T04:32:34.00Z'}, 'dateModified': {'type': 'DateTime', 'value': '2019-09-25T04:32:34.00Z'}}}, 'location': {'type': 'geo:json', 'value': {'type': 'Point', 'coordinates': [0, 0]}, 'metadata': {'dateCreated': {'type': 'DateTime', 'value': '2019-09-25T04:32:34.00Z'}, 'dateModified': {'type': 'DateTime', 'value': '2019-09-25T04:32:34.00Z'}}}}]
INFO:translators.factory:Env variable QL_CONFIG not set, using default value of: 
INFO:translators.factory:no config file specified, using defaults.
INFO:translators.factory:Backend selected for tenant 'None' is: crate
ERROR:app:Exception on /v2/notify [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 143, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/validation.py", line 172, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/validation.py", line 347, in wrapper
    return function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
  File "/src/ngsi-timeseries-api/src/reporter/reporter.py", line 153, in notify
    trans.insert(payload, fiware_s, fiware_sp)
  File "/src/ngsi-timeseries-api/src/translators/crate.py", line 183, in insert
    fiware_servicepath)
  File "/src/ngsi-timeseries-api/src/translators/crate.py", line 264, in _insert_entities_of_type
    self._update_metadata_table(table_name, original_attrs)
  File "/src/ngsi-timeseries-api/src/translators/crate.py", line 364, in _update_metadata_table
    self.cursor.execute(stmt, (table_name, persisted_metadata))
  File "/usr/local/lib/python3.6/site-packages/crate/client/cursor.py", line 54, in execute
    bulk_parameters)
  File "/usr/local/lib/python3.6/site-packages/crate/client/http.py", line 328, in sql
    content = self._json_request('POST', self.path, data=data)
  File "/usr/local/lib/python3.6/site-packages/crate/client/http.py", line 448, in _json_request
    _raise_for_status(response)
  File "/usr/local/lib/python3.6/site-packages/crate/client/http.py", line 187, in _raise_for_status
    error_trace=error_trace)
crate.client.exceptions.ProgrammingError: SQLActionException[SQLParseException: line 1:72: no viable alternative at input 'on duplicate']
192.168.48.3 - - [25/Sep/2019 12:15:23] "POST /v2/notify HTTP/1.1" 500 -
INFO:werkzeug:192.168.48.3 - - [25/Sep/2019 12:15:23] "POST /v2/notify HTTP/1.1" 500 -
```
**My docker-compose.yml file**
```
version: '3.3'

services:
  # # Portainer
  # portainer:
  #   image: portainer/portainer
  #   container_name: portainer_fiware
  #   restart: on-failure
  #   ports:
  #     - "9999:9000"
  #     - "8008:8080"
  #   volumes:
  #     - type: volume
  #       source: vol_portainer_data
  #       target: /data
  #     - type: bind
  #       source: /usr/bin/docker
  #       target: /usr/bin/docker
  #     - type: bind
  #       source: /var/run/docker.sock
  #       target: /var/run/docker.sock

  # Orion Context Broker
  orion:
    image: fiware/orion
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - fiware_orion_net
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG -noCache
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1
  
  # Angente IOT intermediario entre Orion y Dispositivo IOT 
  iot-agent:
    image: fiware/iotagent-ul
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
      - mongo-db
    ports:
      - "4041:4041"
      - "7896:7896"
    environment:
      - "IOTA_CB_HOST=orion"
      - "IOTA_CB_PORT=1026"
      - "IOTA_NORTH_PORT=4041"
      - "IOTA_REGISTRY_TYPE=mongodb"
      - "IOTA_MONGO_HOST=mongo-db"
      - "IOTA_MONGO_PORT=27017"
      - "IOTA_MONGO_DB=iotagentul"
      - "IOTA_HTTP_PORT=7896"
      - "IOTA_PROVIDER_URL=http://iot-agent:4041"
    networks: 
      - fiware_orion_net

# Persistencia de Datos Utilizando Cygnus
  cygnus:
    image: fiware/cygnus-ngsi:latest
    hostname: cygnus
    container_name: fiware-cygnus
    depends_on:
        - mysql-db
        - orion
    ports:
        - "5050:5050"
        - "5080:5080"
    networks:
      - fiware_cygnus_net
    environment:
        - "CYGNUS_MYSQL_HOST=mysql-db"
        - "CYGNUS_MYSQL_PORT=3306"
        - "CYGNUS_MYSQL_USER=root"
        - "CYGNUS_MYSQL_PASS=123"
        - "CYGNUS_LOG_LEVEL=DEBUG"
        - "CYGNUS_SERVICE_PORT=5050"
        - "CYGNUS_API_PORT=5080"

  # Monitorizacion utilizando Grafana
  grafana:
    image: grafana/grafana
    depends_on:
        - crate-db
    ports:
        - "3003:3000"
    environment:
        - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel
    networks:
      - fiware_grafana_net
    volumes:
      - type: volume
        source: vol_grafana-conf
        target: /var/lib/grafana
  # Quantum Leap is persisting Short Term History to Crate-DB
  quantumleap:
    image: smartsdk/quantumleap
    container_name: fiware-quantumleap
    ports:
      - "8668:8668"
    networks:
      - fiware_grafana_net
      - fiware_orion_net
    depends_on:
      - crate-db
      - orion
      - mongo-db
    environment:
      - "CRATE_HOST=http://crate-db"
    healthcheck:
      test: curl --fail -s http://localhost:8668/v2/version || exit 1

  # MONGO DB solo para servicio de Orion
  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: db-mongo
    ports:
      - "27017:27017"
    command: --bind_ip_all --smallfiles
    networks:
      - fiware_orion_net
    volumes:
      - type: volume
        source: vol_mongo-db
        target: /data
    
  # MYSQL solo para utilizar Cygnus  
  mysql-db:
    restart: always
    image: mysql:5.7.16
    hostname: mysql-db
    container_name: mysql-db
    ports:
        - "3306:3306"
    environment:
        - "MYSQL_ROOT_PASSWORD=123"
        - "MYSQL_ROOT_HOST=%"
    networks:
      - fiware_cygnus_net
    volumes: 
      - type: volume
        source: vol_mysql-db
        target: /var/lib/mysql

  # Crate para utilizar Grafana  
  crate-db:
    image: crate
    hostname: crate-db
    container_name: db-crate
    ports:
      # Admin UI
      - "4200:4200"
      # Transport protocol
      - "4300:4300"
   # command: crate -Clicense.enterprise=false -Cauth.host_based.enabled=false  -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
    networks:
      - fiware_grafana_net
    command: -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
    volumes:
      - type: volume
        source: vol_crate-db
        target: /data

# Redes
networks:
  fiware_orion_net:
  fiware_cygnus_net:
  fiware_grafana_net:

# Volumenes para persistir la data.
volumes:
  vol_portainer_data:

  vol_mongo-db:
  vol_mysql-db:
  vol_crate-db:
  vol_grafana-conf:
```
**My Environment:**
 - OS: Ubuntu 18.04.3 LTS
 - PC : Dell 7472
- RAM: 16 Gb
- CPU: i5 8th
 - Docker: 19.03.2, build 6a30dfc
- Docker-Compose: 1.17.1

Thank you for your time.

**Comment by chicco785** [comment]
we will try to reproduce. It would be useful if you have also a payload example for Orion.

**Comment by c0c0n3** [comment]
@MRROOX thank you for reporting this with so much detail. It seems your problem is that the Crate version in the Docker compose is the latest---i.e. `4.x`, which we don't support yet. You should switch to  Crate `3.3`, which we support. If you could please try replacing these lines in `docker-compose.yml`

    crate-db:
        image: crate

with e.g.

    crate-db:
        image: crate:3.3.2
        # note the explicit version number to pull a Crate `3.3` image

and let us know if you're still having trouble. As a matter of fact, I was able to test your notification with a Crate `3.3.2` image and it worked flawlessly for me. You can try this yourself by adding the following test to `src/reporter/tests/test_notify.py`.

    def test_github_254():
        data = {
            'data': [
                {
                    'id': 'DHT22001',
                    'type': 'DHT22',
                    'temperature': {
                        'type': 'Number',
                        'value': 29,
                        'metadata': {
                            'dateCreated': {
                                'type': 'DateTime',
                                'value': '2019-09-25T04:32:34.00Z'
                            },
                            'dateModified': {
                                'type': 'DateTime',
                                'value': '2019-09-25T04:32:41.00Z'
                            }
                        }
                    },
                    'relativeHumidity': {
                        'type': 'Number',
                        'value': '0',
                        'metadata': {
                            'dateCreated': {
                                'type': 'DateTime',
                                'value': '2019-09-25T04:32:34.00Z'
                            },
                            'dateModified': {
                                'type': 'DateTime',
                                'value': '2019-09-25T04:32:34.00Z'
                            }
                        }
                    },
                    'dateObserved': {
                        'type': 'DateTime',
                        'value': '2019-09-30T23:00:00.00Z',
                        'metadata': {
                            'dateCreated': {
                                'type': 'DateTime',
                                'value': '2019-09-25T04:32:34.00Z'
                            },
                            'dateModified': {
                                'type': 'DateTime',
                                'value': '2019-09-25T04:32:34.00Z'
                            }
                        }
                    },
                    'location': {
                        'type': 'geo:json',
                        'value': {
                            'type': 'Point',
                            'coordinates': [0, 0]
                        },
                        'metadata': {
                            'dateCreated': {
                                'type': 'DateTime',
                                'value': '2019-09-25T04:32:34.00Z'
                            },
                            'dateModified': {
                                'type': 'DateTime',
                                'value': '2019-09-25T04:32:34.00Z'
                            }
                        }
                    }
                }
            ]
        }
        url = '{}'.format(notify_url)
        r = requests.post(url, data=json.dumps(data), headers=HEADERS_PUT)
        assert r.status_code == 200

Hope this helps!

**Comment by c0c0n3** [comment]
Just adding some debug info that might come in handy when upgrade to Create 4 (see #256). 
With Crate 4, the statement below, generated by `_update_metadata_table` in the Crate translator, breaks since `on duplicate key` is no longer supported in Crate 4---was already deprecated in `v3`. 

    insert into md_ets_metadata (table_name, entity_attrs)
    values ('"etdht22"', {'entity_type': ('type', 'Text'), ...})
    on duplicate key update entity_attrs = values(entity_attrs)

**Comment by MRROOX** [comment]
Exactly the problem is in the Crate database version, simply changing the image tag to `3.3.2` works without any problem.

### I leave the result of the Quantum Leap container:

```
127.0.0.1 - - [03/Oct/2019 01:37:18] "GET /v2/version HTTP/1.1" 200 -
INFO:reporter.reporter:Received payload: [{'id': 'DHT22001', 'type': 'DHT22', 'temperature': {'type': 'Number', 'value': 29, 'metadata': {'dateCreated': {'type': 'DateTime', 'value': '2019-10-03T01:28:16.00Z'}, 'dateModified': {'type': 'DateTime', 'value': '2019-10-03T01:29:31.00Z'}}}, 'relativeHumidity': {'type': 'Number', 'value': '0', 'metadata': {'dateCreated': {'type': 'DateTime', 'value': '2019-10-03T01:28:16.00Z'}, 'dateModified': {'type': 'DateTime', 'value': '2019-10-03T01:28:16.00Z'}}}, 'dateObserved': {'type': 'DateTime', 'value': '2019-09-30T23:00:00.00Z', 'metadata': {'dateCreated': {'type': 'DateTime', 'value': '2019-10-03T01:28:16.00Z'}, 'dateModified': {'type': 'DateTime', 'value': '2019-10-03T01:28:16.00Z'}}}, 'location': {'type': 'geo:json', 'value': {'type': 'Point', 'coordinates': [0, 0]}, 'metadata': {'dateCreated': {'type': 'DateTime', 'value': '2019-10-03T01:28:16.00Z'}, 'dateModified': {'type': 'DateTime', 'value': '2019-10-03T01:28:16.00Z'}}}}]
INFO:translators.factory:Env variable QL_CONFIG not set, using default value of: 
INFO:translators.factory:no config file specified, using defaults.
INFO:translators.factory:Backend selected for tenant 'None' is: crate
INFO:reporter.reporter:Notification successfully processed
172.23.0.4 - - [03/Oct/2019 01:37:34] "POST /v2/notify HTTP/1.1" 200 -
INFO:werkzeug:172.23.0.4 - - [03/Oct/2019 01:37:34] "POST /v2/notify HTTP/1.1" 200 -
127.0.0.1 - - [03/Oct/2019 01:37:48] "GET /v2/version HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Oct/2019 01:37:48] "GET /v2/version HTTP/1.1" 200 -
127.0.0.1 - - [03/Oct/2019 01:38:18] "GET /v2/version HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Oct/2019 01:38:18] "GET /v2/version HTTP/1.1" 200 -
127.0.0.1 - - [03/Oct/2019 01:38:49] "GET /v2/version HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Oct/2019 01:38:49] "GET /v2/version HTTP/1.1" 200 -
127.0.0.1 - - [03/Oct/2019 01:39:19] "GET /v2/version HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [03/Oct/2019 01:39:19] "GET /v2/version HTTP/1.1" 200 -
```

Works perfect.!

Thank you very much. I really appreciate your time and dedication.

**Comment by c0c0n3** [comment]
Great! I'm happy I could help you!
