### ISSUE TITLE
JSON size on QL component

### ISSUE THREAD

**Issue by netzahdzc** [smartsdk/ngsi-timeseries-api#44]
This error pops up when I post a long Json structure.

```
ERROR in app: Exception on /notify [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "reporter/reporter.py", line 110, in notify
    trans.insert([payload])
  File "/src/ngsi-timeseries-api/translators/crate.py", line 146, in insert
    self.cursor.executemany(stmt, entries)
  File "/usr/local/lib/python3.6/site-packages/crate/client/cursor.py", line 67, in executemany
    self.execute(sql, bulk_parameters=seq_of_parameters)
  File "/usr/local/lib/python3.6/site-packages/crate/client/cursor.py", line 54, in execute
    bulk_parameters)
  File "/usr/local/lib/python3.6/site-packages/crate/client/http.py", line 304, in sql
    content = self._json_request('POST', self.path, data=data)
  File "/usr/local/lib/python3.6/site-packages/crate/client/http.py", line 416, in _json_request
    _raise_for_status(response)
  File "/usr/local/lib/python3.6/site-packages/crate/client/http.py", line 170, in _raise_for_status
    error_trace=error_trace)
crate.client.exceptions.ProgrammingError: IllegalArgumentException[Document contains at least one immense term in field="value" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[45, 49, 46, 48, 50, 57, 54, 44, 52, 46, 54, 52, 54, 53, 53, 44, 45, 49, 46, 54, 51, 50, 53, 52, 44, 50, 48, 49, 55, 45]...', original message: bytes can be at most 32766 in length; got 94981]; nested: MaxBytesLengthExceededException[bytes can be at most 32766 in length; got 94981]; 
```

Please, note that Orion Context Broker does not present any problem handling the long structures. The error was retrieved from the QuantumLeap component.

Could it be possible to extend the size capacity on the component to handle such long files? Personally need it to deal with accelerometer data.

**Comment by taliaga** [comment]
Hi @netzahdzc, thanks for the feedback.

That maximum length is imposed by crate for string columns that are to remain indexable. More info [here in the docs](https://crate.io/docs/crate/reference/en/latest/general/ddl/data-types.html).
I could of course make this a configurable option to disable indexing for string columns (given that QL is mostly aimed to work with measurement values).

In any case, first I'd like to know exactly which is your usecase scenario, to understand which part of your json is landing in a string column. I want to first rule out the possibility that your whole data is landing in a single column instead of in a column-per-attribute. So, do you have a link to your complete POST request so I can investigate here?

**Comment by netzahdzc** [comment]
This is an example of the structure that I use to collect accelerometer data, and of course the acc data is to be larger that the one provided in this sample:

```
{
    "id": "ffffffffff9cbbf4465f0ef30033c587ACC1",
    "type": "Device",
    "category": {
      "type": "Text",
      "value": "sensor",
      "metadata": {}
    },
    "configuration": {
      "type": "StructuredValue",
      "value": {
        "sampleRate": {
          "type": "hz",
          "value": "60"
        },
        "data": {
          "format": "cvs"
        }
      },
      "metadata": {}
    },
    "controlledProperty": {
      "type": "Array",
      "value": [
        "accelerometer"
      ],
      "metadata": {}
    },
    "dateCreated": {
      "type": "Text",
      "value": "2018-01-02T06:32:50.342Z-0600",
      "metadata": {}
    },
    "firmwareVersion": {
      "type": "Text",
      "value": "4.1.2",
      "metadata": {}
    },
    "function": {
      "type": "Array",
      "value": [
        "sensing"
      ],
      "metadata": {}
    },
    "hardwareVersion": {
      "type": "Text",
      "value": "herring",
      "metadata": {}
    },
    "value": {
      "type": "Text",
      "value": "-5.03118,3.12579,2.65317,2018-01-02T06:32:38.569Z-0600 -7.10682,7.31115,2.50693,2018-01-02T06:32:38.769Z-0600 -9.57506,10.6178,2.17802,2018-01-02T06:32:38.813Z-0600 -10.9316,10.6809,0.782812,2018-01-02T06:32:38.852Z-0600 -8.55265,10.6516,-0.69361,2018-01-02T06:32:38.899Z-0600 -6.52885,10.5695,-1.02038,2018-01-02T06:32:38.936Z-0600 -7.16894,10.3603,-1.84796,2018-01-02T06:32:38.967Z-0600 -5.91721,7.56321,-2.48486,2018-01-02T06:32:39.008Z-0600 -4.6794,4.59083,-1.75331,2018-01-02T06:32:39.067Z-0600 -4.55504,2.26496,0.0221505,2018-01-02T06:32:39.097Z-0600 -5.30809,0.396736,1.72985,2018-01-02T06:32:39.126Z-0600 -5.11384,-1.4554,2.06534,2018-01-02T06:32:39.164Z-0600 -4.40386,-3.60277,2.19275,2018-01-02T06:32:39.215Z-0600 -2.38714,-5.70449,3.05358,2018-01-02T06:32:39.242Z-0600 -0.722619,-7.04625,3.27108,2018-01-02T06:32:39.270Z-0600 -0.12468,-8.21711,3.17222,2018-01-02T06:32:39.378Z-0600 -0.309566,-8.53421,3.11433,2018-01-02T06:32:39.425Z-0600 -0.464445,-9.09529,2.53826,2018-01-02T06:32:39.475Z-0600 -0.100185,-9.78513,2.31648,2018-01-02T06:32:39.531Z-0600 0.81452,-10.0904,2.41221,2018-01-02T06:32:39.562Z-0600 0.472975,-9.6404,2.37158,2018-01-02T06:32:39.613Z-0600 0.00371504,-9.71249,1.77723,2018-01-02T06:32:39.655Z-0600 0.0195673,-9.05965,0.735591,2018-01-02T06:32:39.688Z-0600 -0.00632119,-7.87689,0.814601,2018-01-02T06:32:39.719Z-0600 -0.800332,-6.1176,2.04728,2018-01-02T06:32:39.748Z-0600 -2.32122,-4.8079,1.37079,2018-01-02T06:32:39.791Z-0600 -2.27406,-3.55449,-1.43028,2018-01-02T06:32:39.823Z-0600 -2.81073,-0.252083,-0.167375,2018-01-02T06:32:39.857Z-0600 -7.16646,3.69055,3.08977,2018-01-02T06:32:39.893Z-0600 -9.73644,6.37411,2.3174,2018-01-02T06:32:39.933Z-0600 -8.72051,9.99163,1.74776,2018-01-02T06:32:39.963Z-0600 -9.26051,10.4712,0.0579033,2018-01-02T06:32:40.058Z-0600 -10.1712,10.5223,-0.296233,2018-01-02T06:32:40.103Z-0600 -9.7205,10.4854,-1.32548,2018-01-02T06:32:40.141Z-0600 -8.18804,10.3755,-2.28782,2018-01-02T06:32:40.176Z-0600 -6.65297,10.2129,-3.14164,2018-01-02T06:32:40.205Z-0600 -6.34532,8.14379,-4.02191,2018-01-02T06:32:40.256Z-0600 -4.96349,5.13943,-3.36531,2018-01-02T06:32:40.299Z-0600 -3.40856,2.81577,-1.76718,2018-01-02T06:32:40.344Z-0600 -3.36762,0.372472,-1.86883,2018-01-02T06:32:40.385Z-0600 -3.39758,-2.03535,-0.947523,2018-01-02T06:32:40.426Z-0600 -2.6139,-3.99625,0.659874,2018-01-02T06:32:40.474Z-0600 -1.36695,-5.68163,1.8878,2018-01-02T06:32:40.507Z-0600 -0.783676,-6.72655,2.83783,2018-01-02T06:32:40.537Z-0600 -0.161149,-7.40675,3.87302,2018-01-02T06:32:40.584Z-0600 -0.248094,-7.90727,3.81054,2018-01-02T06:32:40.638Z-0600 -1.01649,-7.96305,3.29924,2018-01-02T06:32:40.678Z-0600 -0.679596,-8.06565,2.61643,2018-01-02T06:32:40.749Z-0600 0.202004,-8.46245,3.10902,2018-01-02T06:32:40.819Z-0600 0.850419,-8.43593,3.37564,2018-01-02T06:32:40.863Z-0600 1.14604,-8.28588,3.47873,2018-01-02T06:32:40.892Z-0600 1.18859,-7.60413,3.35333,2018-01-02T06:32:40.922Z-0600 1.06028,-6.60139,2.54228,2018-01-02T06:32:40.959Z-0600 -0.468871,-5.64987,2.29643,2018-01-02T06:32:41.000Z-0600 -1.07828,-4.70655,2.12447,2018-01-02T06:32:41.031Z-0600 -1.62623,-3.4842,3.24489,2018-01-02T06:32:41.060Z-0600 -3.09518,-1.77212,3.83654,2018-01-02T06:32:41.091Z-0600 -5.39826,0.720099,3.69747,2018-01-02T06:32:41.142Z-0600 -7.41661,3.51383,1.92203,2018-01-02T06:32:41.174Z-0600 -8.45015,5.7114,-1.17757,2018-01-02T06:32:41.212Z-0600 -8.67779,7.94358,-2.28253,2018-01-02T06:32:41.241Z-0600 -8.39907,9.90727,-2.42076,2018-01-02T06:32:41.274Z-0600 -8.24647,10.3577,-3.66702,2018-01-02T06:32:41.323Z-0600 -8.75534,10.3531,-5.03776,2018-01-02T06:32:41.359Z-0600 -8.27894,10.3135,-5.20131,2018-01-02T06:32:41.498Z-0600 -6.49569,8.81959,-3.60308,2018-01-02T06:32:41.527Z-0600 -3.9733,6.36251,-2.07328,2018-01-02T06:32:41.581Z-0600 -3.14725,4.47948,-1.86494,2018-01-02T06:32:41.636Z-0600 -2.76855,2.67884,-0.963269,2018-01-02T06:32:41.678Z-0600 -2.96781,1.56749,-0.358155,2018-01-02T06:32:41.739Z-0600 -2.9146,0.22378,0.231593,2018-01-02T06:32:41.782Z-0600 -3.16341,-1.5619,0.50699,2018-01-02T06:32:41.810Z-0600 -2.58173,-3.15508,0.798762,2018-01-02T06:32:41.841Z-0600 -1.64874,-4.49762,1.82773,2018-01-02T06:32:41.884Z-0600 -0.571616,-5.78424,3.32168,2018-01-02T06:32:41.920Z-0600 0.0442731,-6.73973,4.00216,2018-01-02T06:32:41.964Z-0600 0.850423,-7.66652,4.12928,2018-01-02T06:32:41.996Z-0600 1.11283,-8.0208,4.12578,2018-01-02T06:32:42.040Z-0600 1.54399,-8.59774,3.81754,2018-01-02T06:32:42.162Z-0600 2.94946,-8.86252,3.41404,2018-01-02T06:32:42.219Z-0600 3.42615,-8.72886,2.81687,2018-01-02T06:32:42.247Z-0600 3.02103,-8.23633,2.13539,2018-01-02T06:32:42.287Z-0600 2.09686,-7.26003,1.07249,2018-01-02T06:32:42.326Z-0600 1.10612,-6.15971,0.85544,2018-01-02T06:32:42.359Z-0600 -0.282159,-4.5001,0.99995,2018-01-02T06:32:42.402Z-0600 -1.74624,-2.26163,1.25207,2018-01-02T06:32:42.428Z-0600 -4.32273,0.790489,0.879816,2018-01-02T06:32:42.456Z-0600 -6.47999,4.45055,-0.945358,2018-01-02T06:32:42.486Z-0600 -8.16796,7.5302,-2.69206,2018-01-02T06:32:42.528Z-0600 -8.60947,9.71954,-3.81591,2018-01-02T06:32:42.564Z-0600 -8.36819,10.2743,-4.62403,2018-01-02T06:32:42.601Z-0600 -7.41066,10.3209,-4.31531,2018-01-02T06:32:42.631Z-0600 -6.74399,9.92317,-2.52365,2018-01-02T06:32:42.683Z-0600 -6.25589,8.43469,-1.13654,2018-01-02T06:32:42.866Z-0600 -5.03891,7.19558,-0.0846604,2018-01-02T06:32:44.804Z-0600 -4.61396,6.31559,0.500435,2018-01-02T06:32:44.839Z-0600 -4.63447,4.8483,-0.00598142,2018-01-02T06:32:44.869Z-0600 -4.17059,3.66734,0.124975,2018-01-02T06:32:45.002Z-0600 -4.04238,2.78595,0.677809,2018-01-02T06:32:45.063Z-0600 -4.38139,1.13823,0.901133,2018-01-02T06:32:45.140Z-0600... ",
      "metadata": {}
    }
  }
```

**Comment by taliaga** [comment]
Thanks again for the info. I've opened a fix that disables indexing for long text columns because I agree it shouldn't raise an error.

As a side note, that 'value' storing all data as Text looks somewhat weird. Probably using the 3 floats as attributes and letting crate take care of the timestamps would be better. Is that on purpose?

**Comment by netzahdzc** [comment]
great, thanks.

I understand but the design was trying to be as wide as possible, so other applications can use the field for any input they like. For example, they could include an accuracy value, or a fusion data to concentrate orientation values, and so on. Otherwise, we might have many unused attributes. 

Note: this was the first impression, but, since this is a working progress thing, it could eventually evolve, if needed.

Meanwhile, thanks for the comments. I'll be looking forward to hear about the fix's solution.

Cheers!!

**Comment by netzahdzc** [comment]
btw, feel free to close this issues if you consider it appropriated :-)

**Comment by taliaga** [comment]
Forgot to point out [the PR](https://github.com/smartsdk/ngsi-timeseries-api/pull/50) but I guess you figured from the github notification. I'll let you have a look and merge it later today.

I understand what you say. Well, you'll see what to do exactly, I just wanted to raise the heads-up towards the capabilities you loose when saving all as a text in a single field. If not to have one attribute per measurement, maybe saving values as an array of values would be a better compromise considering your will of flexibility (then QL takes care of the historical timestamped values). This last point however may require #36 to be completed, which is already one of the most-likely candidates of next fixes.

**Comment by taliaga** [comment]
@netzahdzc please update your image and let me know if you're still having the issue.

**Comment by netzahdzc** [comment]
Are there any special commands to update? 🙃

**Comment by taliaga** [comment]
Well, depends on how you are deploying it. 

`docker pull smartsdk/quantumleap` if you want to try the new image from the scratch.
Then restart your quantumleap container if you were running it with docker run or docker-compose.

Otherwise `docker service update --image smartsdk:latest quantumleap` if you already have it deployed as a service and the service is called quantumleap. Adjust accordingly of course.
