### ISSUE TITLE
private word data into structure

### ISSUE THREAD

**Issue by netzahdzc** [smartsdk/ngsi-timeseries-api#45]
Below error pops up when I include the word "data" as part of the attributes. No sure whether this is a similar case as the previous issues mentioned  (i.e., about "dataModified"). I mention this, just to let you know that this might be an issue in further developments. I have already worked it around by using a different word.

```
ERROR in app: Exception on /notify [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "reporter/reporter.py", line 89, in notify
    assert len(payload) == 1, 'Multiple data elements in notifications not supported yet'
AssertionError: Multiple data elements in notifications not supported yet
```

**Comment by taliaga** [comment]
Thanks Netza, there are definitively some non-documented considerations for the usecase where orion is taken out of the workflow. I've created #46 to do this.

This error in particular is because orion wraps the notifications in a 'data' json object, so this is where QL picks the notification. Your entity should be wrapped by a `data` key at the root level for it work as you expect. It should not be a problem to have an attribute called data :/

In both this and the other issue you mentioned, be careful with the workarounds because you might not end up with what you want. For example, are you sure all attributes are persisted with a simple rename of the 'data' attribute in this case?

**Comment by netzahdzc** [comment]
ok, thanks for the info. My workaround was to use the work "value" instead of "data".

Feel free to close this issues if you find it convenient.

Cheers!!

**Comment by chicco785** [comment]
@taliaga, i think it may be useful if you pass here an example for netza,
to be sure he understand how wrapped messages are structured.
